package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JRadioButton;
import main.Principal;
import util.Alexa;

/**
 *
 * @author deko_
 */
public class CadColab extends javax.swing.JFrame {

    /**
     * Creates new form CadColab
     */
    public CadColab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCodColab = new javax.swing.JTextField();
        jLogincolab = new javax.swing.JTextField();
        jNomecolab = new javax.swing.JTextField();
        jRadioButtonAdmin = new javax.swing.JRadioButton();
        jRadioButtonUser = new javax.swing.JRadioButton();
        jButtonCadcolab = new javax.swing.JButton();
        jButtonattColab = new javax.swing.JButton();
        jButtonBuscaColab = new javax.swing.JButton();
        jButtonInativaColab = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonNovoColab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Colaboradores");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("Cadastro de colaboradores");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Login");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Senha");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Nível");

        jCodColab.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCodColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodColabActionPerformed(evt);
            }
        });

        jLogincolab.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jNomecolab.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        buttonGroup1.add(jRadioButtonAdmin);
        jRadioButtonAdmin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButtonAdmin.setText("ADMINISTRADOR");
        jRadioButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAdminActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonUser);
        jRadioButtonUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButtonUser.setText("USUÁRIO");

        jButtonCadcolab.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonCadcolab.setText("CADASTRAR");
        jButtonCadcolab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadcolabActionPerformed(evt);
            }
        });

        jButtonattColab.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonattColab.setText("ATUALIZAR");
        jButtonattColab.setMaximumSize(new java.awt.Dimension(97, 23));
        jButtonattColab.setMinimumSize(new java.awt.Dimension(97, 23));
        jButtonattColab.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonattColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonattColabActionPerformed(evt);
            }
        });

        jButtonBuscaColab.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonBuscaColab.setText("BUSCAR");
        jButtonBuscaColab.setMaximumSize(new java.awt.Dimension(97, 23));
        jButtonBuscaColab.setMinimumSize(new java.awt.Dimension(97, 23));
        jButtonBuscaColab.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonBuscaColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaColabActionPerformed(evt);
            }
        });

        jButtonInativaColab.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonInativaColab.setText("INATIVAR");
        jButtonInativaColab.setMaximumSize(new java.awt.Dimension(97, 23));
        jButtonInativaColab.setMinimumSize(new java.awt.Dimension(97, 23));
        jButtonInativaColab.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonInativaColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInativaColabActionPerformed(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPasswordField1.setText("jPasswordField1");

        jButtonNovoColab.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonNovoColab.setText("NOVO");
        jButtonNovoColab.setMaximumSize(new java.awt.Dimension(97, 23));
        jButtonNovoColab.setMinimumSize(new java.awt.Dimension(97, 23));
        jButtonNovoColab.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonNovoColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoColabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jCodColab, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscaColab, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLogincolab)
                            .addComponent(jNomecolab)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonAdmin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonNovoColab, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadcolab, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonattColab, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInativaColab, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCodColab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscaColab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLogincolab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNomecolab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadcolab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonattColab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInativaColab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovoColab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCodColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodColabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodColabActionPerformed

    private void jButtonCadcolabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadcolabActionPerformed
        // TODO add your handling code here:
        if (jLogincolab.getText().matches("") || jPasswordField1.getText().matches("") || jNomecolab.getText().matches("") || (!jRadioButtonAdmin.isSelected() && !jRadioButtonUser.isSelected())) {
            Alexa.escrevaJanela("Verifique se os campos LOGIN, SENHA e NOME estão preenchidos e selecione o nível do usuário!");
        } else {
            Principal.colaborador.setIdUser(Integer.parseInt(jCodColab.getText()));
            Principal.colaborador.setIdLogin(jLogincolab.getText());
            Principal.colaborador.setIdSenha(jPasswordField1.getText());
            Principal.colaborador.setNomeUser(jNomecolab.getText());
            jCodColab.setEditable(true);
            jButtonBuscaColab.setEnabled(true);
            jButtonattColab.setEnabled(true);
            jButtonInativaColab.setEnabled(true);

            if (jRadioButtonAdmin.isSelected()) {
                Principal.colaborador.setNivel("ADMIN");
            } else if (jRadioButtonUser.isSelected()) {
                Principal.colaborador.setNivel("USUARIO");
            }

            boolean cadastrou = Principal.colaboradorDao.inserir(Principal.colaborador);
            if (cadastrou) {
                Alexa.escrevaJanela("Colaborador cadastrado com sucesso!");
                limparCampos();
            } else {
                Alexa.escrevaJanela("Falha ao cadastrar colaborador!");
            }
        }

    }//GEN-LAST:event_jButtonCadcolabActionPerformed

    private void jButtonattColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonattColabActionPerformed
        // TODO add your handling code here:
        if (jLogincolab.getText().matches("") || jPasswordField1.getText().matches("") || jNomecolab.getText().matches("") || (!jRadioButtonAdmin.isSelected() && !jRadioButtonUser.isSelected())) {
            Alexa.escrevaJanela("Verifique se os campos LOGIN, SENHA e NOME estão preenchidos e selecione o nível do usuário!");
        } else {

            Principal.colaborador.setIdUser(Integer.parseInt(jCodColab.getText()));
            Principal.colaborador.setIdLogin(jLogincolab.getText());
            Principal.colaborador.setIdSenha(jPasswordField1.getText());
            Principal.colaborador.setNomeUser(jNomecolab.getText());

            if (jRadioButtonAdmin.isSelected()) {
                Principal.colaborador.setNivel("ADMIN");
            } else if (jRadioButtonUser.isSelected()) {
                Principal.colaborador.setNivel("USUARIO");
            }

            boolean cadastrou = Principal.colaboradorDao.atualizar(Principal.colaborador);
            if (cadastrou) {
                Alexa.escrevaJanela("Colaborador atualizado com sucesso!");
                limparCampos();
            } else {
                Alexa.escrevaJanela("Falha ao atualizar o colaborador!");
            }
        }
    }//GEN-LAST:event_jButtonattColabActionPerformed

    private void jRadioButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAdminActionPerformed

    private void jButtonBuscaColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaColabActionPerformed
        // TODO add your handling code here:
        Principal.colaborador.setIdUser(Integer.parseInt(jCodColab.getText()));
        Principal.colaborador = Principal.colaboradorDao.buscar(Principal.colaborador.getIdUser());

        if (Principal.colaborador == null || Principal.colaborador.getNomeUser() == null) {
            Alexa.escrevaJanela("Nenhum colaborador encontrado com este código!");
        } else {
            jLogincolab.setText(Principal.colaborador.getIdLogin());
            jPasswordField1.setText(Principal.colaborador.getIdSenha());
            jNomecolab.setText(Principal.colaborador.getNomeUser());
            System.out.println("Nível retornado: [" + Principal.colaborador.getNivel() + "]");


            if (Principal.colaborador != null
                    && "ADMIN".equalsIgnoreCase(Principal.colaborador.getNivel())) {
                jRadioButtonAdmin.setSelected(true);
            } else {
                jRadioButtonUser.setSelected(true);
            }
        }
    }//GEN-LAST:event_jButtonBuscaColabActionPerformed

    private void jButtonInativaColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInativaColabActionPerformed
        // TODO add your handling code here:
        Principal.colaborador.setIdUser(Integer.parseInt(jCodColab.getText()));
        boolean inativar = Principal.colaboradorDao.inativar(Principal.colaborador.getIdUser());
        if (inativar) {
            Alexa.escrevaJanela("Colaborador inativado com sucesso!");
            limparCampos();
        } else {
            Alexa.escrevaJanela("Colaborador não encontrado!");
        }
    }//GEN-LAST:event_jButtonInativaColabActionPerformed

    private void jButtonNovoColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoColabActionPerformed
        // TODO add your handling code here:
        int novoId = gerarProximoIdColab();
        jCodColab.setText(String.valueOf(novoId));
        jCodColab.setEditable(false);
        jButtonBuscaColab.setEnabled(false);
        jButtonattColab.setEnabled(false);
        jButtonInativaColab.setEnabled(false);
        jLogincolab.setText("");
        jPasswordField1.setText("");
        jNomecolab.setText("");

    }//GEN-LAST:event_jButtonNovoColabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadColab.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadColab.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadColab.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadColab.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editojButtonCadcolab
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadColab().setVisible(true);
            }
        });
    }

    public int gerarProximoIdColab() {
        int novoId = 1;

        String sqlSelect = "SELECT ultimo_id FROM gerador_id WHERE tabela = 'colaborador' FOR UPDATE";
        String sqlUpdate = "UPDATE gerador_id SET ultimo_id = ? WHERE tabela = 'colaborador'";

        try (Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/crud?characterEncoding=utf-8", "root", "025507")) {

            conn.setAutoCommit(false); // Inicia transação

            try (PreparedStatement psSelect = conn.prepareStatement(sqlSelect); ResultSet rs = psSelect.executeQuery()) {

                if (rs.next()) {
                    novoId = rs.getInt("ultimo_id") + 1;
                }
            }

            try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
                psUpdate.setInt(1, novoId);
                psUpdate.executeUpdate();
            }

            conn.commit();

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return novoId;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBuscaColab;
    private javax.swing.JButton jButtonCadcolab;
    private javax.swing.JButton jButtonInativaColab;
    private javax.swing.JButton jButtonNovoColab;
    private javax.swing.JButton jButtonattColab;
    private javax.swing.JTextField jCodColab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jLogincolab;
    private javax.swing.JTextField jNomecolab;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButtonAdmin;
    private javax.swing.JRadioButton jRadioButtonUser;
    // End of variables declaration//GEN-END:variables
private void limparCampos() {
        jCodColab.setText("");
        jLogincolab.setText("");
        jPasswordField1.setText("");
        jNomecolab.setText("");

    }

}
