/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import main.Principal;
import util.Alexa;

/**
 *
 * @author deko_
 */
public class CadInsumo extends javax.swing.JFrame {

    /**
     * Creates new form CadInsumos
     */
    public CadInsumo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCodigoin = new javax.swing.JTextField();
        jNomein = new javax.swing.JTextField();
        jButtonCadIns = new javax.swing.JButton();
        jButtonAttIns = new javax.swing.JButton();
        jButtonBuscIns = new javax.swing.JButton();
        jButtonInativarIns = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cadastro de insumos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Nome");

        jCodigoin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jNomein.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jNomein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeinActionPerformed(evt);
            }
        });

        jButtonCadIns.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonCadIns.setText("CADASTRAR");
        jButtonCadIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadInsActionPerformed(evt);
            }
        });

        jButtonAttIns.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonAttIns.setText("ATUALIZAR");
        jButtonAttIns.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonAttIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttInsActionPerformed(evt);
            }
        });

        jButtonBuscIns.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonBuscIns.setText("BUSCAR");
        jButtonBuscIns.setMaximumSize(new java.awt.Dimension(97, 23));
        jButtonBuscIns.setMinimumSize(new java.awt.Dimension(97, 23));
        jButtonBuscIns.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonBuscIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscInsActionPerformed(evt);
            }
        });

        jButtonInativarIns.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonInativarIns.setText("INATIVAR");
        jButtonInativarIns.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonInativarIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInativarInsActionPerformed(evt);
            }
        });

        jButtonNovo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonNovo.setText("NOVO");
        jButtonNovo.setMaximumSize(new java.awt.Dimension(97, 23));
        jButtonNovo.setMinimumSize(new java.awt.Dimension(97, 23));
        jButtonNovo.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadIns, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAttIns, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInativarIns, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCodigoin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButtonBuscIns, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jNomein)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCodigoin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscIns, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNomein, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadIns, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAttIns, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInativarIns, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jNomeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeinActionPerformed

    private void jButtonCadInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadInsActionPerformed
        // TODO add your handling code here:
        if (jNomein.getText().matches("")){
            Alexa.escrevaJanela("Preencha o campo NOME!");
        }else{
            Principal.insumo.setIdInsumo(Integer.parseInt(jCodigoin.getText()));
            Principal.insumo.setNomeInsumo(jNomein.getText());
            jCodigoin.setEditable(true);
            jButtonAttIns.setEnabled(true);
            jButtonBuscIns.setEnabled(true);
            jButtonInativarIns.setEnabled(true);
            
            boolean cadastrou = Principal.insumoDao.inserir(Principal.insumo);
        if (cadastrou) {
            Alexa.escrevaJanela("Insumo cadastrado com sucesso!");
            limparCampos();
        }else{
            Alexa.escrevaJanela("Falha ao cadastrar insumo!");
        }
        }
    }//GEN-LAST:event_jButtonCadInsActionPerformed

    private void jButtonAttInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttInsActionPerformed
        // TODO add your handling code here:
        if (jNomein.getText().matches("")){
            Alexa.escrevaJanela("Preencha o campo NOME!");
        }else{
        Principal.insumo.setIdInsumo(Integer.parseInt(jCodigoin.getText()));
        Principal.insumo.setNomeInsumo(jNomein.getText());
        
        boolean atualizou = Principal.insumoDao.atualizar(Principal.insumo);
        if (atualizou){
            Alexa.escrevaJanela("Insumo atualizado com sucesso!");
            limparCampos();
        }else{
            Alexa.escrevaJanela("Falha ao cadastrar o insumo!");
        }
        }
    }//GEN-LAST:event_jButtonAttInsActionPerformed

    private void jButtonBuscInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscInsActionPerformed
        // TODO add your handling code here:
        Principal.insumo.setIdInsumo(Integer.parseInt(jCodigoin.getText()));
        Principal.insumo = Principal.insumoDao.buscar(Principal.insumo.getIdInsumo());
        if (Principal.insumo == null || Principal.insumo.getNomeInsumo() == null){
            Alexa.escrevaJanela("Nenhum insumo encontrado com este código!");
        }else{
            jNomein.setText(Principal.insumo.getNomeInsumo());
        }
    }//GEN-LAST:event_jButtonBuscInsActionPerformed

    private void jButtonInativarInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInativarInsActionPerformed
        // TODO add your handling code here:
        Principal.insumo.setIdInsumo(Integer.parseInt(jCodigoin.getText()));
        boolean inativar = Principal.insumoDao.inativar(Principal.insumo.getIdInsumo());
        if (inativar) {
            Alexa.escrevaJanela("Insumo inativado com sucesso!");
            limparCampos();
        } else {
            Alexa.escrevaJanela("Insumo não encontrado!");
        }
    }//GEN-LAST:event_jButtonInativarInsActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        int novoId = gerarProximoIdInsumo();
        jCodigoin.setText(String.valueOf(novoId));
        jCodigoin.setEditable(false);
        jButtonAttIns.setEnabled(false);
        jButtonBuscIns.setEnabled(false);
        jButtonInativarIns.setEnabled(false);
        jNomein.setText("");
    }//GEN-LAST:event_jButtonNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadInsumo().setVisible(true);
            }
        });
    }
    
    public int gerarProximoIdInsumo() {
    int novoId = 1;

    String sqlSelect = "SELECT ultimo_id FROM gerador_id WHERE tabela = 'insumo' FOR UPDATE";
    String sqlUpdate = "UPDATE gerador_id SET ultimo_id = ? WHERE tabela = 'insumo'";

    try (Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/crud?characterEncoding=utf-8", "root", "025507")) {

        conn.setAutoCommit(false); // Inicia transação

        try (PreparedStatement psSelect = conn.prepareStatement(sqlSelect);
             ResultSet rs = psSelect.executeQuery()) {

            if (rs.next()) {
                novoId = rs.getInt("ultimo_id") + 1;
            }
        }

        try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
            psUpdate.setInt(1, novoId);
            psUpdate.executeUpdate();
        }

        conn.commit();

    } catch (SQLException e) {
        e.printStackTrace();
    }

    return novoId;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAttIns;
    private javax.swing.JButton jButtonBuscIns;
    private javax.swing.JButton jButtonCadIns;
    private javax.swing.JButton jButtonInativarIns;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JTextField jCodigoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNomein;
    // End of variables declaration//GEN-END:variables
private void limparCampos() {
    jCodigoin.setText("");
    jNomein.setText("");
}
}
