package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import main.Principal;
import util.Alexa;

public class CadProd extends javax.swing.JFrame {

    public int gerarProximoId() {
        int proximoId = 1; // Valor inicial caso o banco esteja vazio.
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crud?characterEncoding=utf-8", "root", "025507"); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT MAX(idProduto) AS idProduto from produto")) {
            if (rs.next()) {
                proximoId = rs.getInt("idProduto") + 1;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            Alexa.escrevaJanela("Error \n" + e);
        }
        return proximoId;
    }

    public CadProd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButtonCadProd = new javax.swing.JButton();
        jButtonAttProd = new javax.swing.JButton();
        jButtonBuscProd = new javax.swing.JButton();
        jButtonInativarProd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDescPro = new javax.swing.JTextField();
        jCodProd = new javax.swing.JTextField();
        jValorPro = new javax.swing.JTextField();
        jValidPro = new javax.swing.JTextField();
        jLotePro = new javax.swing.JTextField();
        jMarcaPro = new javax.swing.JTextField();
        jForProd = new javax.swing.JTextField();
        jButtonNovoProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cadastro de produtos");

        jButtonCadProd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonCadProd.setText("CADASTRAR");
        jButtonCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadProdActionPerformed(evt);
            }
        });

        jButtonAttProd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonAttProd.setText("ATUALIZAR");
        jButtonAttProd.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonAttProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttProdActionPerformed(evt);
            }
        });

        jButtonBuscProd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonBuscProd.setText("BUSCAR");
        jButtonBuscProd.setMaximumSize(new java.awt.Dimension(97, 23));
        jButtonBuscProd.setMinimumSize(new java.awt.Dimension(97, 23));
        jButtonBuscProd.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonBuscProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscProdActionPerformed(evt);
            }
        });

        jButtonInativarProd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonInativarProd.setText("INATIVAR");
        jButtonInativarProd.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonInativarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInativarProdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Descrição");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Valor");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Validade");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Lote");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Marca");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Fornecedor");

        jDescPro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jCodProd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jValorPro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jValidPro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLotePro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMarcaPro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jForProd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jButtonNovoProduto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonNovoProduto.setText("NOVO");
        jButtonNovoProduto.setMaximumSize(new java.awt.Dimension(97, 23));
        jButtonNovoProduto.setMinimumSize(new java.awt.Dimension(97, 23));
        jButtonNovoProduto.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jButtonAttProd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jButtonInativarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jValorPro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jValidPro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLotePro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonBuscProd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jDescPro)
                        .addComponent(jForProd)
                        .addComponent(jMarcaPro))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDescPro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jValorPro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jValidPro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLotePro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMarcaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jForProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAttProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInativarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadProdActionPerformed
        // TODO add your handling code here:
        if (jDescPro.getText().matches("")) {
            Alexa.escrevaJanela("Preencha o campo DESCRIÇÃO!");
        } else {
            Principal.produto.setIdProduto(Integer.parseInt(jCodProd.getText()));
            Principal.produto.setDescProduto(jDescPro.getText());
            Principal.produto.setValorProduto(jValorPro.getText());
            Principal.produto.setValidadeProduto(jValidPro.getText());
            Principal.produto.setLoteProduto(jLotePro.getText());
            Principal.produto.setMarcaProduto(jMarcaPro.getText());
            Principal.produto.setFornecedorProduto(jForProd.getText());
            jCodProd.setEditable(true);
            jButtonBuscProd.setEnabled(true);
            jButtonAttProd.setEnabled(true);
            jButtonInativarProd.setEnabled(true);

            boolean cadastrou = Principal.produtoDao.inserir(Principal.produto);
            if (cadastrou) {
                Alexa.escrevaJanela("Produto cadastrado com sucesso!");
                limparCampos();
            } else {
                Alexa.escrevaJanela("Falha ao cadastrar produto!");
            }
        }
    }//GEN-LAST:event_jButtonCadProdActionPerformed

    private void jButtonAttProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttProdActionPerformed
        // TODO add your handling code here:
        if (jCodProd.getText().matches("") || jDescPro.getText().matches("")) {
            Alexa.escrevaJanela("Preencha o campo DESCRIÇÃO!");
        } else {
            Principal.produto.setIdProduto(Integer.parseInt(jCodProd.getText()));
            Principal.produto.setDescProduto(jDescPro.getText());
            Principal.produto.setValorProduto(jValorPro.getText());
            Principal.produto.setValidadeProduto(jValidPro.getText());
            Principal.produto.setLoteProduto(jLotePro.getText());
            Principal.produto.setMarcaProduto(jMarcaPro.getText());
            Principal.produto.setFornecedorProduto(jForProd.getText());

            boolean atualizou = Principal.produtoDao.atualizar(Principal.produto);
            if (atualizou) {
                Alexa.escrevaJanela("Produto atualizado com sucesso!");
                limparCampos();
            } else {
                Alexa.escrevaJanela("Falha ao atualizar o produto!");
            }
        }
    }//GEN-LAST:event_jButtonAttProdActionPerformed

    private void jButtonBuscProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscProdActionPerformed
        // TODO add your handling code here:
        Principal.produto.setIdProduto(Integer.parseInt(jCodProd.getText()));
        Principal.produto = Principal.produtoDao.buscar(Principal.produto.getIdProduto());

        if (Principal.produto == null || Principal.produto.getDescProduto() == null) {
            Alexa.escrevaJanela("Nenhum produto encontrado com este código!");
        } else {
            jDescPro.setText(Principal.produto.getDescProduto());
            jValorPro.setText(Principal.produto.getValorProduto());
            jValidPro.setText(Principal.produto.getValidadeProduto());
            jLotePro.setText(Principal.produto.getLoteProduto());
            jMarcaPro.setText(Principal.produto.getMarcaProduto());
            jForProd.setText(Principal.produto.getFornecedorProduto());
        }
    }//GEN-LAST:event_jButtonBuscProdActionPerformed

    private void jButtonInativarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInativarProdActionPerformed
        // TODO add your handling code here:
        Principal.produto.setIdProduto(Integer.parseInt(jCodProd.getText()));
        boolean inativar = Principal.produtoDao.inativar(Principal.produto.getIdProduto());
        if (inativar) {
            Alexa.escrevaJanela("Produto inativado com sucesso!");
        } else {
            Alexa.escrevaJanela("Produto não encontrado!");
        }
    }//GEN-LAST:event_jButtonInativarProdActionPerformed

    private void jButtonNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoProdutoActionPerformed
        // TODO add your handling code here:
        int novoId = gerarProximoIdProduto();
        jCodProd.setText(String.valueOf(novoId));
        jCodProd.setEditable(false);
        jButtonBuscProd.setEnabled(false);
        jButtonAttProd.setEnabled(false);
        jButtonInativarProd.setEnabled(false);
        jDescPro.setText("");
        jValorPro.setText("");
        jValidPro.setText("");
        jLotePro.setText("");
        jMarcaPro.setText("");
        jForProd.setText("");
    }//GEN-LAST:event_jButtonNovoProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProd().setVisible(true);
            }
        });
    }

    public int gerarProximoIdProduto() {
        int novoId = 1;

        String sqlSelect = "SELECT ultimo_id FROM gerador_id WHERE tabela = 'produto' FOR UPDATE";
        String sqlUpdate = "UPDATE gerador_id SET ultimo_id = ? WHERE tabela = 'produto'";

        try (Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/crud?characterEncoding=utf-8", "root", "025507")) {

            conn.setAutoCommit(false); // Inicia transação

            try (PreparedStatement psSelect = conn.prepareStatement(sqlSelect); ResultSet rs = psSelect.executeQuery()) {

                if (rs.next()) {
                    novoId = rs.getInt("ultimo_id") + 1;
                }
            }

            try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
                psUpdate.setInt(1, novoId);
                psUpdate.executeUpdate();
            }

            conn.commit();

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return novoId;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAttProd;
    private javax.swing.JButton jButtonBuscProd;
    private javax.swing.JButton jButtonCadProd;
    private javax.swing.JButton jButtonInativarProd;
    private javax.swing.JButton jButtonNovoProduto;
    private javax.swing.JTextField jCodProd;
    private javax.swing.JTextField jDescPro;
    private javax.swing.JTextField jForProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jLotePro;
    private javax.swing.JTextField jMarcaPro;
    private javax.swing.JTextField jValidPro;
    private javax.swing.JTextField jValorPro;
    // End of variables declaration//GEN-END:variables
private void limparCampos() {
        jCodProd.setText("");
        jDescPro.setText("");
        jValorPro.setText("");
        jValidPro.setText("");
        jLotePro.setText("");
        jMarcaPro.setText("");
        jForProd.setText("");
    }
}
