package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import main.Principal;
import util.Alexa;

/**
 *
 * @author deko_
 */
public class CadProced extends javax.swing.JFrame {

    /**
     * Creates new form CadProced
     */
    public CadProced() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCodpro = new javax.swing.JTextField();
        jNomepro = new javax.swing.JTextField();
        jValorpro = new javax.swing.JTextField();
        jButtonCadpro = new javax.swing.JButton();
        jButtonAttpro = new javax.swing.JButton();
        jButtonBuscpro = new javax.swing.JButton();
        jButtonInapro = new javax.swing.JButton();
        jButtonNovoPro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("Cadastro de procedimentos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Valor");

        jCodpro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jNomepro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jValorpro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jValorpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorproActionPerformed(evt);
            }
        });

        jButtonCadpro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonCadpro.setText("CADASTRAR");
        jButtonCadpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadproActionPerformed(evt);
            }
        });

        jButtonAttpro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonAttpro.setText("ATUALIZAR");
        jButtonAttpro.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonAttpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttproActionPerformed(evt);
            }
        });

        jButtonBuscpro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonBuscpro.setText("BUSCAR");
        jButtonBuscpro.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonBuscpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscproActionPerformed(evt);
            }
        });

        jButtonInapro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonInapro.setText("INATIVAR");
        jButtonInapro.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonInapro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInaproActionPerformed(evt);
            }
        });

        jButtonNovoPro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonNovoPro.setText("NOVO");
        jButtonNovoPro.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonNovoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNomepro)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jValorpro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCodpro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBuscpro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNovoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonCadpro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonAttpro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonInapro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCodpro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBuscpro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNomepro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jValorpro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadpro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAttpro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInapro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadproActionPerformed
        // TODO add your handling code here:
        if (jNomepro.getText().matches("") || jValorpro.getText().matches("")) {
            Alexa.escrevaJanela("Preencha o campo NOME e o campo VALOR!");
        } else {
            Principal.procedimento.setIdProcedimento(Integer.parseInt(jCodpro.getText()));
            Principal.procedimento.setNomeProcedimento(jNomepro.getText());
            Principal.procedimento.setValorProcedimento(jValorpro.getText());

            boolean cadastrou = Principal.procedimentoDao.inserir(Principal.procedimento);
            if (cadastrou) {
                Alexa.escrevaJanela("Procedimento cadastrado com sucesso!");
                limparCampos();
                jCodpro.setEditable(true);
                jButtonBuscpro.setEnabled(true);
                jButtonAttpro.setEnabled(true);
                jButtonInapro.setEnabled(true);
            } else {
                Alexa.escrevaJanela("Falha ao cadastrar procedimento!");
            }
        }
    }//GEN-LAST:event_jButtonCadproActionPerformed

    private void jButtonAttproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttproActionPerformed
        // TODO add your handling code here:
        if (jNomepro.getText().matches("") || jValorpro.getText().matches("")) {
            Alexa.escrevaJanela("Preencha os campos NOME e VALOR!");
        } else {
            Principal.procedimento.setIdProcedimento(Integer.parseInt(jCodpro.getText()));
            Principal.procedimento.setNomeProcedimento(jNomepro.getText());
            Principal.procedimento.setValorProcedimento(jValorpro.getText());

            boolean cadastrou = Principal.procedimentoDao.atualizar(Principal.procedimento);
            if (cadastrou) {
                Alexa.escrevaJanela("Procedimento atualizado com sucesso!");
                limparCampos();
            } else {
                Alexa.escrevaJanela("Falha ao atualizar o procedimento!");
            }
        }
    }//GEN-LAST:event_jButtonAttproActionPerformed

    private void jButtonBuscproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscproActionPerformed
        // TODO add your handling code here:
        Principal.procedimento.setIdProcedimento(Integer.parseInt(jCodpro.getText()));
        Principal.procedimento = Principal.procedimentoDao.buscar(Principal.procedimento.getIdProcedimento());
        if (Principal.procedimento == null || Principal.procedimento.getNomeProcedimento() == null){
            Alexa.escrevaJanela("Nenhum prodecimento encontrado com este código!");
        }else{
            jNomepro.setText(Principal.procedimento.getNomeProcedimento());
            jValorpro.setText(Principal.procedimento.getValorProcedimento());
        }
    }//GEN-LAST:event_jButtonBuscproActionPerformed

    private void jButtonInaproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInaproActionPerformed
        // TODO add your handling code here:
        Principal.procedimento.setIdProcedimento(Integer.parseInt(jCodpro.getText()));
        boolean inativar = Principal.procedimentoDao.inativar(Principal.procedimento.getIdProcedimento());
        if (inativar) {
            Alexa.escrevaJanela("Procedimento inativado com sucesso");
        } else {
            Alexa.escrevaJanela("Procedimento não encontrado!");
        }
    }//GEN-LAST:event_jButtonInaproActionPerformed

    private void jValorproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValorproActionPerformed

    private void jButtonNovoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoProActionPerformed
        // TODO add your handling code here:
        int novoId = gerarProximoIdProcedimento();
        jCodpro.setText(String.valueOf(novoId));
        jCodpro.setEditable(false);
        jButtonBuscpro.setEnabled(false);
        jButtonAttpro.setEnabled(false);
        jButtonInapro.setEnabled(false);
        jNomepro.setText("");
        jValorpro.setText("");
    }//GEN-LAST:event_jButtonNovoProActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProced().setVisible(true);
            }
        });
    }
    
    public int gerarProximoIdProcedimento() {
    int novoId = 1;

    String sqlSelect = "SELECT ultimo_id FROM gerador_id WHERE tabela = 'procedimento' FOR UPDATE";
    String sqlUpdate = "UPDATE gerador_id SET ultimo_id = ? WHERE tabela = 'procedimento'";

    try (Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/crud?characterEncoding=utf-8", "root", "025507")) {

        conn.setAutoCommit(false); // Inicia transação

        try (PreparedStatement psSelect = conn.prepareStatement(sqlSelect);
             ResultSet rs = psSelect.executeQuery()) {

            if (rs.next()) {
                novoId = rs.getInt("ultimo_id") + 1;
            }
        }

        try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
            psUpdate.setInt(1, novoId);
            psUpdate.executeUpdate();
        }

        conn.commit();

    } catch (SQLException e) {
        e.printStackTrace();
    }

    return novoId;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAttpro;
    private javax.swing.JButton jButtonBuscpro;
    private javax.swing.JButton jButtonCadpro;
    private javax.swing.JButton jButtonInapro;
    private javax.swing.JButton jButtonNovoPro;
    private javax.swing.JTextField jCodpro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNomepro;
    private javax.swing.JTextField jValorpro;
    // End of variables declaration//GEN-END:variables
private void limparCampos() {
        jCodpro.setText("");
        jNomepro.setText("");
        jValorpro.setText("");
    }
}
