package view;

import connection.FabricaConexao;
import entidade.Sessao;
import java.sql.*;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import main.Principal;
import util.Alexa;

/**
 *
 * @author deko_
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private void mostrarAniversariantes() {
        painelAniversarios.removeAll();

        java.util.List<String> hoje = buscarAniversariantes(true);
        java.util.List<String> amanha = buscarAniversariantes(false);

        painelAniversarios.add(new javax.swing.JLabel("Aniversariantes de HOJE:"));
        if (hoje.isEmpty()) {
            painelAniversarios.add(new javax.swing.JLabel(" - Nenhum"));
        } else {
            for (String nome : hoje) {
                painelAniversarios.add(new javax.swing.JLabel(" - " + nome));
            }
        }

        painelAniversarios.add(javax.swing.Box.createVerticalStrut(10));

        painelAniversarios.add(new javax.swing.JLabel("Aniversariantes de AMANHÃ:"));
        if (amanha.isEmpty()) {
            painelAniversarios.add(new javax.swing.JLabel(" - Nenhum"));
        } else {
            for (String nome : amanha) {
                painelAniversarios.add(new javax.swing.JLabel(" - " + nome));
            }
        }

        painelAniversarios.revalidate();
        painelAniversarios.repaint();
    }

    private java.util.List<String> buscarAniversariantes(boolean hoje) {
        java.util.List<String> lista = new java.util.ArrayList<>();

        String sql
                = "SELECT c.nomeCliente, t.foneCliente1 "
                + "FROM cliente c "
                + "JOIN (SELECT idCliente, MIN(idTelefone) AS idTelefone FROM telefone GROUP BY idCliente) tt "
                + "  ON c.idCliente = tt.idCliente "
                + "JOIN telefone t ON t.idTelefone = tt.idTelefone "
                + "WHERE DATE_FORMAT(STR_TO_DATE(c.dtnCliente, '%d/%m/%Y'), '%m-%d') = "
                + (hoje ? "DATE_FORMAT(CURDATE(), '%m-%d')" : "DATE_FORMAT(CURDATE() + INTERVAL 1 DAY, '%m-%d')")
                + " ORDER BY SUBSTRING(c.dtnCliente, 1, 2) ASC";

        try (Connection conn = FabricaConexao.getConnection(); Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                String nome = rs.getString("nomeCliente");
                String telefone = rs.getString("foneCliente1");
                lista.add(nome + " (" + telefone + ")");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao buscar aniversariantes:\n" + e.getMessage());
        }

        return lista;
    }

    public MenuPrincipal() {
        initComponents();

        painelAniversarios = new javax.swing.JPanel();
        painelAniversarios.setLayout(new javax.swing.BoxLayout(painelAniversarios, javax.swing.BoxLayout.Y_AXIS));
        painelAniversarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Aniversariantes"));
        painelAniversarios.setOpaque(false); // fundo transparente para ver a imagem
        getContentPane().add(painelAniversarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 200));
        getContentPane().setComponentZOrder(painelAniversarios, 0);
        
        mostrarAniversariantes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuCadCli = new javax.swing.JMenuItem();
        jMenuCadColab = new javax.swing.JMenuItem();
        jMenuCadInsu = new javax.swing.JMenuItem();
        jMenuCadProced = new javax.swing.JMenuItem();
        jMenuCadProd = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItemRelClie = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1024, 890));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 890));

        jMenu5.setText("AGENDAR");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem1.setText("AGENDAMENTOS");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("CADASTRAR");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuCadCli.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuCadCli.setText("CLIENTES");
        jMenuCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadCliActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuCadCli);

        jMenuCadColab.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuCadColab.setText("COLABORADOR");
        jMenuCadColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadColabActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuCadColab);

        jMenuCadInsu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuCadInsu.setText("INSUMOS");
        jMenuCadInsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadInsuActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuCadInsu);

        jMenuCadProced.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuCadProced.setText("PROCEDIMENTOS");
        jMenuCadProced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadProcedActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuCadProced);

        jMenuCadProd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuCadProd.setText("PRODUTO");
        jMenuCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadProdActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuCadProd);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("RELATÓRIOS");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem3.setText("AGENDAMENTOS");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem4.setText("AGENDAMENTOS PERÍODO");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem5.setText("ANIVERSARIANTES");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenuItemRelClie.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItemRelClie.setText("CLIENTES");
        jMenuItemRelClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelClieActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemRelClie);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem9.setText("COLABORADOR");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem7.setText("INSUMOS");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem8.setText("PROCEDIMENTOS");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuBar2.add(jMenu7);

        jMenu1.setText("FINANCEIRO");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem6.setText("CONTAS A RECEBER");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem10.setText("CONTAS A PAGAR");
        jMenu1.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem11.setText("CAD. DE DESPESAS");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar2.add(jMenu1);

        jMenu8.setText("SAIR");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem2.setText("SAIR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem2);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadCliActionPerformed
        // TODO add your handling code here:
        CadClieNew objtelacadclie = new CadClieNew();
        objtelacadclie.setVisible(true);
    }//GEN-LAST:event_jMenuCadCliActionPerformed

    private void jMenuCadInsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadInsuActionPerformed
        // TODO add your handling code here:
        String nivel = Sessao.usuarioLogado.getNivel(); // Pega o nível do usuário logado

        if (nivel.equalsIgnoreCase("ADMIN")) {
            // Usuário tem permissão
            CadInsumo objtelacadinsu = new CadInsumo();
            objtelacadinsu.setVisible(true);
        } else {
            // Usuário não tem permissão
            JOptionPane.showMessageDialog(null, "Acesso negado: Você não tem nível administrativo para acessar este módulo.");
        }

    }//GEN-LAST:event_jMenuCadInsuActionPerformed

    private void jMenuCadProcedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadProcedActionPerformed
        // TODO add your handling code here:
        String nivel = Sessao.usuarioLogado.getNivel(); // Pega o nível do usuário logado

        if (nivel.equalsIgnoreCase("ADMIN")) {
            // Usuário tem permissão
            CadProced objtelacadproced = new CadProced();
            objtelacadproced.setVisible(true);
        } else {
            // Usuário não tem permissão
            JOptionPane.showMessageDialog(null, "Acesso negado: Você não tem nível administrativo para acessar este módulo.");
        }

    }//GEN-LAST:event_jMenuCadProcedActionPerformed

    private void jMenuItemRelClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelClieActionPerformed
        // TODO add your handling code here:
        Principal.clientes = Principal.clienteDao.getListaCliente();
        if (Principal.clientes.isEmpty()) {
            Alexa.escrevaJanela("Não existe nenhum cliente cadastrado ");
        } else {
            RelClie relclie = new RelClie();
            relclie.setLocationRelativeTo(null);
            relclie.setVisible(true);
        }

    }//GEN-LAST:event_jMenuItemRelClieActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuCadColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadColabActionPerformed
        // TODO add your handling code here:
        String nivel = Sessao.usuarioLogado.getNivel(); // Pega o nível do usuário logado

        if (nivel.equalsIgnoreCase("ADMIN")) {
            // Usuário tem permissão
            CadColab objtelacadcolab = new CadColab();
            objtelacadcolab.setVisible(true);
        } else {
            // Usuário não tem permissão
            JOptionPane.showMessageDialog(null, "Acesso negado: Você não tem nível administrativo para acessar este módulo.");
        }
    }//GEN-LAST:event_jMenuCadColabActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Agenda objagendae = new Agenda();
        objagendae.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Principal.insumos = Principal.insumoDao.getListaInsumo();
        if (Principal.insumos.isEmpty()) {
            Alexa.escrevaJanela("Não existe nenhum insumo cadastrado");
        } else {
            RelIns relins = new RelIns();
            relins.setLocationRelativeTo(null);
            relins.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Principal.procedimentos = Principal.procedimentoDao.getListaProcedimento();
        if (Principal.procedimentos.isEmpty()) {
            Alexa.escrevaJanela("Não existe nenhum procedimento cadastrado");
        } else {
            RelProced relproced = new RelProced();
            relproced.setLocationRelativeTo(null);
            relproced.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        Principal.colaboradores = Principal.colaboradorDao.getListaColaborador();
        if (Principal.colaboradores.isEmpty()) {
            Alexa.escrevaJanela("Não existe nenhum colaborador cadastrado");
        } else {
            RelColab relcolab = new RelColab();
            relcolab.setLocationRelativeTo(null);
            relcolab.setVisible(true);
        }

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Principal.agendamentos = Principal.agendamentodDao.getListaAgendamento();
        if (Principal.agendamentos.isEmpty()) {
            Alexa.escrevaJanela("Não existem agendamentos");
        } else {
            RelAgenda relagenda = new RelAgenda();
            relagenda.setLocationRelativeTo(null);
            relagenda.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadProdActionPerformed
        // TODO add your handling code here:
        String nivel = Sessao.usuarioLogado.getNivel(); // Pega o nível do usuário logado

        if (nivel.equalsIgnoreCase("ADMIN")) {
            // Usuário tem permissão
            CadProd objtcadpro = new CadProd();
            objtcadpro.setVisible(true);
        } else {
            // Usuário não tem permissão
            JOptionPane.showMessageDialog(null, "Acesso negado: Você não tem nível administrativo para acessar este módulo.");
        }

    }//GEN-LAST:event_jMenuCadProdActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        String nivel = Sessao.usuarioLogado.getNivel(); // Pega o nível do usuário logado

        if (nivel.equalsIgnoreCase("ADMIN")) {
            // Usuário tem permissão
            RelAgTotal objtrelagtotal = new RelAgTotal();
            objtrelagtotal.setVisible(true);
        } else {
            // Usuário não tem permissão
            JOptionPane.showMessageDialog(null, "Acesso negado: Você não tem nível administrativo para acessar este módulo.");
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        RelAniversarios objtrelaniver = new RelAniversarios();
        objtrelaniver.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        String nivel = Sessao.usuarioLogado.getNivel(); // Pega o nível do usuário logado

        if (nivel.equalsIgnoreCase("ADMIN")) {
            // Usuário tem permissão
            CadContaReceber objtcontareceb = new CadContaReceber();
            objtcontareceb.setVisible(true);
        } else {
            // Usuário não tem permissão
            JOptionPane.showMessageDialog(null, "Acesso negado: Você não tem nível administrativo para acessar este módulo.");
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        String nivel = Sessao.usuarioLogado.getNivel(); // Pega o nível do usuário logado

        if (nivel.equalsIgnoreCase("ADMIN")) {
            // Usuário tem permissão
            CadDespesa objtdespesa = new CadDespesa();
            objtdespesa.setVisible(true);
        } else {
            // Usuário não tem permissão
            JOptionPane.showMessageDialog(null, "Acesso negado: Você não tem nível administrativo para acessar este módulo.");
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuCadCli;
    private javax.swing.JMenuItem jMenuCadColab;
    private javax.swing.JMenuItem jMenuCadInsu;
    private javax.swing.JMenuItem jMenuCadProced;
    private javax.swing.JMenuItem jMenuCadProd;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemRelClie;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JPanel painelAniversarios;
}
