package view;

import connection.FabricaConexao;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author deko_
 */
public class SelInsumo2 extends javax.swing.JDialog {
    
    private String nomeexpo;

    public String getNomeexpo() {
        return nomeexpo;
    }

    public void setNomeexpo(String nomeexpo) {
        this.nomeexpo = nomeexpo;
    }
    
    FabricaConexao CONEXAO = new FabricaConexao();
    DefaultListModel MODELO;
    int Enter = 0;

    String[] Codigp;
    
    /**
     * Creates new form SelInsumo2
     */
    public SelInsumo2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CONEXAO.conecta();
        MostraPesquisa();
        Lista3.setVisible(false);
        Lista3.setVisible(false);
        MODELO = new DefaultListModel();
        Lista3.setModel(MODELO);
        Lista3.setModel(MODELO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeI = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextFieldNomeI2 = new javax.swing.JLabel();
        jTextFieldCodigoI = new javax.swing.JLabel();
        Lista3 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("CÓDIGO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("NOME");

        jTextFieldNomeI.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldNomeI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeIActionPerformed(evt);
            }
        });
        jTextFieldNomeI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomeIKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setText("SELECIONAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Lista3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Lista3.setOpaque(false);
        Lista3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lista3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lista3MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DIGITE O NOME DO INSUMO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jTextFieldCodigoI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jTextFieldNomeI2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeI, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lista3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNomeI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCodigoI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldNomeI2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Lista3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.nomeexpo = jTextFieldNomeI2.getText();
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNomeIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeIActionPerformed
        // TODO add your handling code here:
        Lista3.setVisible(true);
        Enter = 1;
    }//GEN-LAST:event_jTextFieldNomeIActionPerformed

    private void jTextFieldNomeIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeIKeyReleased
        // TODO add your handling code here:
        if (Enter == 0)
            ListaDePesquisa();
        else
            Enter = 0;
    }//GEN-LAST:event_jTextFieldNomeIKeyReleased

    private void Lista3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Lista3MouseClicked

    private void Lista3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista3MousePressed
        // TODO add your handling code here:
        MostraPesquisa();
        Lista3.setVisible(true);
    }//GEN-LAST:event_Lista3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelInsumo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelInsumo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelInsumo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelInsumo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelInsumo2 dialog = new SelInsumo2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lista3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jTextFieldCodigoI;
    private javax.swing.JTextField jTextFieldNomeI;
    private javax.swing.JLabel jTextFieldNomeI2;
    // End of variables declaration//GEN-END:variables
public void ListaDePesquisa() {
        try {CONEXAO.executaSQL("SELECT * FROM insumo where nomeInsumo like '" + jTextFieldNomeI.getText() + "%' ORDER BY nomeInsumo");
            MODELO.removeAllElements();
            int v = 0;
            Codigp = new String[10];
            while (CONEXAO.resultset.next() & v < 10) {
                MODELO.addElement(CONEXAO.resultset.getString("nomeInsumo"));
                Codigp[v] = CONEXAO.resultset.getString("idInsumo");
                v++;
            }
            if (v >= 1) {
                Lista3.setVisible(true);
            } else {
                Lista3.setVisible(false);
            }

            ResultadoPesquisa();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao listar dados" + erro);
        }
    }
    
        public void MostraPesquisa() {
        int Linha = Lista3.getSelectedIndex();
        if (Linha >= 0) {
            CONEXAO.executaSQL("SELECT * FROM insumo where nomeInsumo like '" + "" + jTextFieldNomeI.getText() + "%' ORDER BY nomeInsumo Limit "+ Linha +", 1 ");
            ResultadoPesquisa();
        }

    }
    
    
    public void ResultadoPesquisa() {
        try {
            CONEXAO.resultset.first();
            jTextFieldCodigoI.setText(CONEXAO.resultset.getString("idInsumo"));
            jTextFieldNomeI2.setText(CONEXAO.resultset.getString("nomeInsumo"));
            } catch (SQLException erro) {
        }
}
}
